# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\66912\Desktop\calculator.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.value = 0
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(894, 748)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setAnimated(True)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.button_1 = QtWidgets.QPushButton(self.centralwidget)
        self.button_1.setGeometry(QtCore.QRect(150, 470, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.button_1.setFont(font)
        self.button_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_1.setMouseTracking(False)
        self.button_1.setObjectName("button_1")
        self.button_2 = QtWidgets.QPushButton(self.centralwidget)
        self.button_2.setGeometry(QtCore.QRect(250, 470, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.button_2.setFont(font)
        self.button_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_2.setMouseTracking(False)
        self.button_2.setObjectName("button_2")
        self.button_3 = QtWidgets.QPushButton(self.centralwidget)
        self.button_3.setGeometry(QtCore.QRect(350, 470, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.button_3.setFont(font)
        self.button_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_3.setMouseTracking(False)
        self.button_3.setObjectName("button_3")
        self.button_4 = QtWidgets.QPushButton(self.centralwidget)
        self.button_4.setGeometry(QtCore.QRect(150, 370, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.button_4.setFont(font)
        self.button_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_4.setMouseTracking(False)
        self.button_4.setObjectName("button_4")
        self.button_5 = QtWidgets.QPushButton(self.centralwidget)
        self.button_5.setGeometry(QtCore.QRect(250, 370, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.button_5.setFont(font)
        self.button_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_5.setMouseTracking(False)
        self.button_5.setObjectName("button_5")
        self.button_6 = QtWidgets.QPushButton(self.centralwidget)
        self.button_6.setGeometry(QtCore.QRect(350, 370, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.button_6.setFont(font)
        self.button_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_6.setMouseTracking(False)
        self.button_6.setObjectName("button_6")
        self.button_7 = QtWidgets.QPushButton(self.centralwidget)
        self.button_7.setGeometry(QtCore.QRect(150, 270, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.button_7.setFont(font)
        self.button_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_7.setMouseTracking(False)
        self.button_7.setObjectName("button_7")
        self.button_8 = QtWidgets.QPushButton(self.centralwidget)
        self.button_8.setGeometry(QtCore.QRect(250, 270, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.button_8.setFont(font)
        self.button_8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_8.setMouseTracking(False)
        self.button_8.setObjectName("button_8")
        self.button_9 = QtWidgets.QPushButton(self.centralwidget)
        self.button_9.setGeometry(QtCore.QRect(350, 270, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.button_9.setFont(font)
        self.button_9.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_9.setMouseTracking(False)
        self.button_9.setTabletTracking(False)
        self.button_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.button_9.setAutoFillBackground(False)
        self.button_9.setStyleSheet("")
        self.button_9.setAutoDefault(False)
        self.button_9.setDefault(False)
        self.button_9.setFlat(False)
        self.button_9.setObjectName("button_9")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 0, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(450, 10, 118, 23))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setItalic(False)
        font.setUnderline(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.progressBar.setFont(font)
        self.progressBar.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.progressBar.setProperty("value", 99)
        self.progressBar.setObjectName("progressBar")
        self.LCD = QtWidgets.QLCDNumber(self.centralwidget)
        self.LCD.setGeometry(QtCore.QRect(30, 40, 541, 91))
        self.LCD.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.LCD.setLineWidth(3)
        self.LCD.setDigitCount(12)
        self.LCD.setObjectName("LCD")
        self.button_dot = QtWidgets.QPushButton(self.centralwidget)
        self.button_dot.setGeometry(QtCore.QRect(250, 570, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.button_dot.setFont(font)
        self.button_dot.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_dot.setMouseTracking(False)
        self.button_dot.setObjectName("button_dot")
        self.button_as = QtWidgets.QPushButton(self.centralwidget)
        self.button_as.setGeometry(QtCore.QRect(350, 570, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.button_as.setFont(font)
        self.button_as.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_as.setMouseTracking(False)
        self.button_as.setObjectName("button_as")
        self.button_0 = QtWidgets.QPushButton(self.centralwidget)
        self.button_0.setGeometry(QtCore.QRect(150, 570, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.button_0.setFont(font)
        self.button_0.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_0.setMouseTracking(False)
        self.button_0.setObjectName("button_0")
        self.button_plus = QtWidgets.QPushButton(self.centralwidget)
        self.button_plus.setGeometry(QtCore.QRect(450, 270, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.button_plus.setFont(font)
        self.button_plus.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_plus.setMouseTracking(False)
        self.button_plus.setTabletTracking(False)
        self.button_plus.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.button_plus.setAutoFillBackground(False)
        self.button_plus.setStyleSheet("")
        self.button_plus.setAutoDefault(False)
        self.button_plus.setDefault(False)
        self.button_plus.setFlat(False)
        self.button_plus.setObjectName("button_plus")
        self.button_multi = QtWidgets.QPushButton(self.centralwidget)
        self.button_multi.setGeometry(QtCore.QRect(450, 470, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.button_multi.setFont(font)
        self.button_multi.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_multi.setMouseTracking(False)
        self.button_multi.setObjectName("button_multi")
        self.button_minus = QtWidgets.QPushButton(self.centralwidget)
        self.button_minus.setGeometry(QtCore.QRect(450, 370, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.button_minus.setFont(font)
        self.button_minus.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_minus.setMouseTracking(False)
        self.button_minus.setObjectName("button_minus")
        self.button_divid = QtWidgets.QPushButton(self.centralwidget)
        self.button_divid.setGeometry(QtCore.QRect(450, 570, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.button_divid.setFont(font)
        self.button_divid.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_divid.setMouseTracking(False)
        self.button_divid.setObjectName("button_divid")
        self.button_bracketopen = QtWidgets.QPushButton(self.centralwidget)
        self.button_bracketopen.setGeometry(QtCore.QRect(350, 170, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.button_bracketopen.setFont(font)
        self.button_bracketopen.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_bracketopen.setMouseTracking(False)
        self.button_bracketopen.setTabletTracking(False)
        self.button_bracketopen.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.button_bracketopen.setAutoFillBackground(False)
        self.button_bracketopen.setStyleSheet("")
        self.button_bracketopen.setAutoDefault(False)
        self.button_bracketopen.setDefault(False)
        self.button_bracketopen.setFlat(False)
        self.button_bracketopen.setObjectName("button_bracketopen")
        self.button_bracketclose = QtWidgets.QPushButton(self.centralwidget)
        self.button_bracketclose.setGeometry(QtCore.QRect(450, 170, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.button_bracketclose.setFont(font)
        self.button_bracketclose.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_bracketclose.setMouseTracking(False)
        self.button_bracketclose.setTabletTracking(False)
        self.button_bracketclose.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.button_bracketclose.setAutoFillBackground(False)
        self.button_bracketclose.setStyleSheet("")
        self.button_bracketclose.setAutoDefault(False)
        self.button_bracketclose.setDefault(False)
        self.button_bracketclose.setFlat(False)
        self.button_bracketclose.setObjectName("button_bracketclose")
        self.button_power = QtWidgets.QPushButton(self.centralwidget)
        self.button_power.setGeometry(QtCore.QRect(150, 170, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.button_power.setFont(font)
        self.button_power.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_power.setMouseTracking(False)
        self.button_power.setTabletTracking(False)
        self.button_power.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.button_power.setAutoFillBackground(False)
        self.button_power.setStyleSheet("")
        self.button_power.setAutoDefault(False)
        self.button_power.setDefault(False)
        self.button_power.setFlat(False)
        self.button_power.setObjectName("button_power")
        self.button_sqrt = QtWidgets.QPushButton(self.centralwidget)
        self.button_sqrt.setGeometry(QtCore.QRect(250, 170, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.button_sqrt.setFont(font)
        self.button_sqrt.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_sqrt.setMouseTracking(False)
        self.button_sqrt.setTabletTracking(False)
        self.button_sqrt.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.button_sqrt.setAutoFillBackground(False)
        self.button_sqrt.setStyleSheet("")
        self.button_sqrt.setAutoDefault(False)
        self.button_sqrt.setDefault(False)
        self.button_sqrt.setFlat(False)
        self.button_sqrt.setObjectName("button_sqrt")
        self.button_left = QtWidgets.QPushButton(self.centralwidget)
        self.button_left.setGeometry(QtCore.QRect(560, 570, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.button_left.setFont(font)
        self.button_left.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_left.setMouseTracking(False)
        self.button_left.setTabletTracking(False)
        self.button_left.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.button_left.setAutoFillBackground(False)
        self.button_left.setStyleSheet("")
        self.button_left.setAutoDefault(False)
        self.button_left.setDefault(False)
        self.button_left.setFlat(False)
        self.button_left.setObjectName("button_left")
        self.button_right = QtWidgets.QPushButton(self.centralwidget)
        self.button_right.setGeometry(QtCore.QRect(670, 570, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.button_right.setFont(font)
        self.button_right.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_right.setMouseTracking(False)
        self.button_right.setTabletTracking(False)
        self.button_right.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.button_right.setAutoFillBackground(False)
        self.button_right.setStyleSheet("")
        self.button_right.setAutoDefault(False)
        self.button_right.setDefault(False)
        self.button_right.setFlat(False)
        self.button_right.setObjectName("button_right")
        self.button_pi = QtWidgets.QPushButton(self.centralwidget)
        self.button_pi.setGeometry(QtCore.QRect(560, 470, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.button_pi.setFont(font)
        self.button_pi.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_pi.setMouseTracking(False)
        self.button_pi.setTabletTracking(False)
        self.button_pi.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.button_pi.setAutoFillBackground(False)
        self.button_pi.setStyleSheet("")
        self.button_pi.setAutoDefault(False)
        self.button_pi.setDefault(False)
        self.button_pi.setFlat(False)
        self.button_pi.setObjectName("button_pi")
        self.button_ln = QtWidgets.QPushButton(self.centralwidget)
        self.button_ln.setGeometry(QtCore.QRect(670, 470, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.button_ln.setFont(font)
        self.button_ln.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_ln.setMouseTracking(False)
        self.button_ln.setTabletTracking(False)
        self.button_ln.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.button_ln.setAutoFillBackground(False)
        self.button_ln.setStyleSheet("")
        self.button_ln.setAutoDefault(False)
        self.button_ln.setDefault(False)
        self.button_ln.setFlat(False)
        self.button_ln.setObjectName("button_ln")
        self.button_Abs = QtWidgets.QPushButton(self.centralwidget)
        self.button_Abs.setGeometry(QtCore.QRect(560, 370, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.button_Abs.setFont(font)
        self.button_Abs.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_Abs.setMouseTracking(False)
        self.button_Abs.setTabletTracking(False)
        self.button_Abs.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.button_Abs.setAutoFillBackground(False)
        self.button_Abs.setStyleSheet("")
        self.button_Abs.setAutoDefault(False)
        self.button_Abs.setDefault(False)
        self.button_Abs.setFlat(False)
        self.button_Abs.setObjectName("button_Abs")
        self.button_delete = QtWidgets.QPushButton(self.centralwidget)
        self.button_delete.setGeometry(QtCore.QRect(560, 270, 181, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.button_delete.setFont(font)
        self.button_delete.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_delete.setMouseTracking(False)
        self.button_delete.setTabletTracking(False)
        self.button_delete.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.button_delete.setAutoFillBackground(False)
        self.button_delete.setStyleSheet("")
        self.button_delete.setAutoDefault(False)
        self.button_delete.setDefault(False)
        self.button_delete.setFlat(False)
        self.button_delete.setObjectName("button_delete")
        self.button_e = QtWidgets.QPushButton(self.centralwidget)
        self.button_e.setGeometry(QtCore.QRect(670, 370, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.button_e.setFont(font)
        self.button_e.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_e.setMouseTracking(False)
        self.button_e.setTabletTracking(False)
        self.button_e.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.button_e.setAutoFillBackground(False)
        self.button_e.setStyleSheet("")
        self.button_e.setAutoDefault(False)
        self.button_e.setDefault(False)
        self.button_e.setFlat(False)
        self.button_e.setObjectName("button_e")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 894, 27))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        
        #number
        self.button_0.clicked.connect(self.funcButton_0)        # 0
        self.button_1.clicked.connect(self.funcButton_1)        # 1
        self.button_2.clicked.connect(self.funcButton_2)        # 2
        self.button_3.clicked.connect(self.funcButton_3)        # 3
        self.button_4.clicked.connect(self.funcButton_4)        # 4
        self.button_5.clicked.connect(self.funcButton_5)        # 5
        self.button_6.clicked.connect(self.funcButton_6)        # 6
        self.button_7.clicked.connect(self.funcButton_7)        # 7
        self.button_8.clicked.connect(self.funcButton_8)        # 8
        self.button_9.clicked.connect(self.funcButton_9)        # 9
        self.button_dot.clicked.connect(self.funcButton_dot)    # . 
        self.button_as.clicked.connect(self.funcButton_as)      # = 
        #Operator
        self.button_plus.clicked.connect(self.funcButton_plus)     # +
        self.button_minus.clicked.connect(self.funcButton_minus)   # -
        self.button_multi.clicked.connect(self.funcButton_multi)   # x
        self.button_divid.clicked.connect(self.funcButton_divid)   # /
        self.button_power.clicked.connect(self.funcButton_power)   # X^2
        self.button_sqrt.clicked.connect(self.funcButton_sqrt)     # sqrt
        #sign
        self.button_e.clicked.connect(self.funcButton_e)        # e
        self.button_ln.clicked.connect(self.funcButton_ln)      # ln
        self.button_pi.clicked.connect(self.funcButton_pi)      # pi
        self.button_Abs.clicked.connect(self.funcButton_Abs)    # |X|
        #bracket
        self.button_bracketclose.clicked.connect(self.funcButton_bracketOpen)# (
        self.button_bracketopen.clicked.connect(self.funcButton_bracketClose)# )
        #slide
        self.button_left.clicked.connect(self.funcButton_left)     # <
        self.button_right.clicked.connect(self.funcButton_right)   # > 
        self.button_delete.clicked.connect(self.funcButton_delete)
         


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.button_1.setText(_translate("MainWindow", "1"))
        self.button_2.setText(_translate("MainWindow", "2"))
        self.button_3.setText(_translate("MainWindow", "3"))
        self.button_4.setText(_translate("MainWindow", "4"))
        self.button_5.setText(_translate("MainWindow", "5"))
        self.button_6.setText(_translate("MainWindow", "6"))
        self.button_7.setText(_translate("MainWindow", "7"))
        self.button_8.setText(_translate("MainWindow", "8"))
        self.button_9.setText(_translate("MainWindow", "9"))
        self.label.setText(_translate("MainWindow", "Calculator by ChiNoMyA"))
        self.button_dot.setText(_translate("MainWindow", "."))
        self.button_as.setText(_translate("MainWindow", "="))
        self.button_0.setText(_translate("MainWindow", "0"))
        self.button_plus.setText(_translate("MainWindow", "+"))
        self.button_multi.setText(_translate("MainWindow", "x"))
        self.button_minus.setText(_translate("MainWindow", "-"))
        self.button_divid.setText(_translate("MainWindow", "/"))
        self.button_bracketopen.setText(_translate("MainWindow", "("))
        self.button_bracketclose.setText(_translate("MainWindow", ")"))
        self.button_power.setText(_translate("MainWindow", "x^2"))
        self.button_sqrt.setText(_translate("MainWindow", "√2"))
        self.button_left.setText(_translate("MainWindow", "<"))
        self.button_right.setText(_translate("MainWindow", ">"))
        self.button_pi.setText(_translate("MainWindow", "π"))
        self.button_ln.setText(_translate("MainWindow", "ln"))
        self.button_Abs.setText(_translate("MainWindow", "|x|"))
        self.button_delete.setText(_translate("MainWindow", "C"))
        self.button_e.setText(_translate("MainWindow", "e"))
    def funcButton_0(self):
        self.value =  (int(str(self.value) +'0') )
        self.LCD.display(self.value)
    def funcButton_1(self):
        self.value =  (int(str(self.value) +'1') )
        self.LCD.display(self.value)
    def funcButton_2(self):
        self.value =  (int(str(self.value) +'2') )
        self.LCD.display(self.value)
    def funcButton_3(self):
        self.value =  (int(str(self.value) +'3') )
        self.LCD.display(self.value)
    def funcButton_4(self):
        self.value =  (int(str(self.value) +'4') )
        self.LCD.display(self.value)
    def funcButton_5(self):
        self.value =  (int(str(self.value) +'5') )
        self.LCD.display(self.value)
    def funcButton_6(self):
        self.value =  (int(str(self.value) +'6') )
        self.LCD.display(self.value)
    def funcButton_7(self):
        self.value =  (int(str(self.value) +'7') )
        self.LCD.display(self.value)
    def funcButton_8(self):
        self.value =  (int(str(self.value) +'8') )
        self.LCD.display(self.value)
    def funcButton_9(self):
        self.value =  (int(str(self.value) +'9') )
        self.LCD.display(self.value)
    def funcButton_dot(self):
        self.value =  (int(str(self.value) +'.0') )
        self.LCD.display(self.value)
    def funcButton_as(self):
        pass
    def funcButton_plus(self):
        pass
    def funcButton_minus(self):
        pass
    def funcButton_multi(self):
        pass
    def funcButton_divid(self):
        pass
    def funcButton_power(self):
        pass
    def funcButton_sqrt(self):
        pass
    def funcButton_e(self):
        pass
    def funcButton_ln(self):
        pass
    def funcButton_pi(self):
        pass
    def funcButton_Abs(self):
        pass
    def funcButton_bracketOpen(self):
        pass
    def funcButton_bracketClose(self):
        pass
    def funcButton_left(self):
        pass
    def funcButton_right(self):
        pass
    def funcButton_delete(self):
        self.value = 0
        self.LCD.display(self.value)
    #mod log ประวัติ

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
