# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\66912\Desktop\calculator.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(520, 660)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setAnimated(True)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.button_1 = QtWidgets.QPushButton(self.centralwidget)
        self.button_1.setGeometry(QtCore.QRect(10, 440, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.button_1.setFont(font)
        self.button_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_1.setMouseTracking(False)
        self.button_1.setObjectName("button_1")
        self.button_2 = QtWidgets.QPushButton(self.centralwidget)
        self.button_2.setGeometry(QtCore.QRect(110, 440, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.button_2.setFont(font)
        self.button_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_2.setMouseTracking(False)
        self.button_2.setObjectName("button_2")
        self.button_3 = QtWidgets.QPushButton(self.centralwidget)
        self.button_3.setGeometry(QtCore.QRect(210, 440, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.button_3.setFont(font)
        self.button_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_3.setMouseTracking(False)
        self.button_3.setObjectName("button_3")
        self.button_4 = QtWidgets.QPushButton(self.centralwidget)
        self.button_4.setGeometry(QtCore.QRect(10, 340, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.button_4.setFont(font)
        self.button_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_4.setMouseTracking(False)
        self.button_4.setObjectName("button_4")
        self.button_5 = QtWidgets.QPushButton(self.centralwidget)
        self.button_5.setGeometry(QtCore.QRect(110, 340, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.button_5.setFont(font)
        self.button_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_5.setMouseTracking(False)
        self.button_5.setObjectName("button_5")
        self.button_6 = QtWidgets.QPushButton(self.centralwidget)
        self.button_6.setGeometry(QtCore.QRect(210, 340, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.button_6.setFont(font)
        self.button_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_6.setMouseTracking(False)
        self.button_6.setObjectName("button_6")
        self.button_7 = QtWidgets.QPushButton(self.centralwidget)
        self.button_7.setGeometry(QtCore.QRect(10, 240, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.button_7.setFont(font)
        self.button_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_7.setMouseTracking(False)
        self.button_7.setObjectName("button_7")
        self.button_8 = QtWidgets.QPushButton(self.centralwidget)
        self.button_8.setGeometry(QtCore.QRect(110, 240, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.button_8.setFont(font)
        self.button_8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_8.setMouseTracking(False)
        self.button_8.setObjectName("button_8")
        self.button_9 = QtWidgets.QPushButton(self.centralwidget)
        self.button_9.setGeometry(QtCore.QRect(210, 240, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.button_9.setFont(font)
        self.button_9.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_9.setMouseTracking(False)
        self.button_9.setTabletTracking(False)
        self.button_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.button_9.setAutoFillBackground(False)
        self.button_9.setStyleSheet("")
        self.button_9.setAutoDefault(False)
        self.button_9.setDefault(False)
        self.button_9.setFlat(False)
        self.button_9.setObjectName("button_9")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, -10, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(390, 0, 118, 23))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setItalic(False)
        font.setUnderline(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.progressBar.setFont(font)
        self.progressBar.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.progressBar.setProperty("value", 100)
        self.progressBar.setObjectName("progressBar")
        self.button_dot = QtWidgets.QPushButton(self.centralwidget)
        self.button_dot.setGeometry(QtCore.QRect(110, 540, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.button_dot.setFont(font)
        self.button_dot.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_dot.setMouseTracking(False)
        self.button_dot.setObjectName("button_dot")
        self.button_as = QtWidgets.QPushButton(self.centralwidget)
        self.button_as.setGeometry(QtCore.QRect(410, 440, 91, 191))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.button_as.setFont(font)
        self.button_as.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_as.setMouseTracking(False)
        self.button_as.setObjectName("button_as")
        self.button_0 = QtWidgets.QPushButton(self.centralwidget)
        self.button_0.setGeometry(QtCore.QRect(10, 540, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.button_0.setFont(font)
        self.button_0.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_0.setMouseTracking(False)
        self.button_0.setObjectName("button_0")
        self.button_plus = QtWidgets.QPushButton(self.centralwidget)
        self.button_plus.setGeometry(QtCore.QRect(310, 240, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.button_plus.setFont(font)
        self.button_plus.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_plus.setMouseTracking(False)
        self.button_plus.setTabletTracking(False)
        self.button_plus.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.button_plus.setAutoFillBackground(False)
        self.button_plus.setStyleSheet("")
        self.button_plus.setAutoDefault(False)
        self.button_plus.setDefault(False)
        self.button_plus.setFlat(False)
        self.button_plus.setObjectName("button_plus")
        self.button_multi = QtWidgets.QPushButton(self.centralwidget)
        self.button_multi.setGeometry(QtCore.QRect(310, 440, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.button_multi.setFont(font)
        self.button_multi.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_multi.setMouseTracking(False)
        self.button_multi.setObjectName("button_multi")
        self.button_minus = QtWidgets.QPushButton(self.centralwidget)
        self.button_minus.setGeometry(QtCore.QRect(310, 340, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.button_minus.setFont(font)
        self.button_minus.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_minus.setMouseTracking(False)
        self.button_minus.setObjectName("button_minus")
        self.button_divid = QtWidgets.QPushButton(self.centralwidget)
        self.button_divid.setGeometry(QtCore.QRect(310, 540, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.button_divid.setFont(font)
        self.button_divid.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_divid.setMouseTracking(False)
        self.button_divid.setObjectName("button_divid")
        self.button_bracketopen = QtWidgets.QPushButton(self.centralwidget)
        self.button_bracketopen.setGeometry(QtCore.QRect(210, 140, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.button_bracketopen.setFont(font)
        self.button_bracketopen.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_bracketopen.setMouseTracking(False)
        self.button_bracketopen.setTabletTracking(False)
        self.button_bracketopen.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.button_bracketopen.setAutoFillBackground(False)
        self.button_bracketopen.setStyleSheet("")
        self.button_bracketopen.setAutoDefault(False)
        self.button_bracketopen.setDefault(False)
        self.button_bracketopen.setFlat(False)
        self.button_bracketopen.setObjectName("button_bracketopen")
        self.button_bracketclose = QtWidgets.QPushButton(self.centralwidget)
        self.button_bracketclose.setGeometry(QtCore.QRect(310, 140, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.button_bracketclose.setFont(font)
        self.button_bracketclose.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_bracketclose.setMouseTracking(False)
        self.button_bracketclose.setTabletTracking(False)
        self.button_bracketclose.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.button_bracketclose.setAutoFillBackground(False)
        self.button_bracketclose.setStyleSheet("")
        self.button_bracketclose.setAutoDefault(False)
        self.button_bracketclose.setDefault(False)
        self.button_bracketclose.setFlat(False)
        self.button_bracketclose.setObjectName("button_bracketclose")
        self.button_power = QtWidgets.QPushButton(self.centralwidget)
        self.button_power.setGeometry(QtCore.QRect(10, 140, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.button_power.setFont(font)
        self.button_power.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_power.setMouseTracking(False)
        self.button_power.setTabletTracking(False)
        self.button_power.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.button_power.setAutoFillBackground(False)
        self.button_power.setStyleSheet("")
        self.button_power.setAutoDefault(False)
        self.button_power.setDefault(False)
        self.button_power.setFlat(False)
        self.button_power.setObjectName("button_power")
        self.button_sqrt = QtWidgets.QPushButton(self.centralwidget)
        self.button_sqrt.setGeometry(QtCore.QRect(110, 140, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.button_sqrt.setFont(font)
        self.button_sqrt.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_sqrt.setMouseTracking(False)
        self.button_sqrt.setTabletTracking(False)
        self.button_sqrt.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.button_sqrt.setAutoFillBackground(False)
        self.button_sqrt.setStyleSheet("")
        self.button_sqrt.setAutoDefault(False)
        self.button_sqrt.setDefault(False)
        self.button_sqrt.setFlat(False)
        self.button_sqrt.setObjectName("button_sqrt")
        self.button_Clear = QtWidgets.QPushButton(self.centralwidget)
        self.button_Clear.setGeometry(QtCore.QRect(410, 240, 91, 191))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.button_Clear.setFont(font)
        self.button_Clear.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_Clear.setMouseTracking(False)
        self.button_Clear.setTabletTracking(False)
        self.button_Clear.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.button_Clear.setAutoFillBackground(False)
        self.button_Clear.setStyleSheet("")
        self.button_Clear.setAutoDefault(False)
        self.button_Clear.setDefault(False)
        self.button_Clear.setFlat(False)
        self.button_Clear.setObjectName("button_Clear")
        self.button_plus_minus = QtWidgets.QPushButton(self.centralwidget)
        self.button_plus_minus.setGeometry(QtCore.QRect(210, 540, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.button_plus_minus.setFont(font)
        self.button_plus_minus.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_plus_minus.setMouseTracking(False)
        self.button_plus_minus.setTabletTracking(False)
        self.button_plus_minus.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.button_plus_minus.setAutoFillBackground(False)
        self.button_plus_minus.setStyleSheet("")
        self.button_plus_minus.setAutoDefault(False)
        self.button_plus_minus.setDefault(False)
        self.button_plus_minus.setFlat(False)
        self.button_plus_minus.setObjectName("button_plus_minus")
        self.button_Delete = QtWidgets.QPushButton(self.centralwidget)
        self.button_Delete.setGeometry(QtCore.QRect(410, 140, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.button_Delete.setFont(font)
        self.button_Delete.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_Delete.setMouseTracking(False)
        self.button_Delete.setTabletTracking(False)
        self.button_Delete.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.button_Delete.setAutoFillBackground(False)
        self.button_Delete.setStyleSheet("")
        self.button_Delete.setAutoDefault(False)
        self.button_Delete.setDefault(False)
        self.button_Delete.setFlat(False)
        self.button_Delete.setObjectName("button_Delete")
        self.Textbar = QtWidgets.QTextBrowser(self.centralwidget)
        self.Textbar.setGeometry(QtCore.QRect(10, 30, 491, 101))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.Textbar.setFont(font)
        self.Textbar.setObjectName("Textbar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 521, 27))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


        #----------------------------------------------------------------
        self.result = 0
        self.Precision = ""
        self.button_as.clicked.connect(self.click_as)
        self.button_1.clicked.connect(self.click_1)
        self.button_2.clicked.connect(self.click_2)
        self.button_3.clicked.connect(self.click_3)
        self.button_4.clicked.connect(self.click_4)
        self.button_5.clicked.connect(self.click_5)
        self.button_6.clicked.connect(self.click_6)
        self.button_7.clicked.connect(self.click_7)
        self.button_8.clicked.connect(self.click_8)
        self.button_9.clicked.connect(self.click_9)
        self.button_0.clicked.connect(self.click_0)
        self.button_dot.clicked.connect(self.click_dot)
        self.button_plus.clicked.connect(self.click_plus)
        self.button_multi.clicked.connect(self.click_multi)
        self.button_minus.clicked.connect(self.click_minus)
        self.button_divid.clicked.connect(self.click_divid)
        self.button_bracketopen.clicked.connect(self.click_bracketopen)
        self.button_bracketclose.clicked.connect(self.click_bracketclose)
        self.button_power.clicked.connect(self.click_power)
        self.button_sqrt.clicked.connect(self.click_sqrt)
        self.button_Clear.clicked.connect(self.click_Clear)
        self.button_plus_minus.clicked.connect(self.click_plus_minus)
        self.button_Delete.clicked.connect(self.click_Delete)

    def click_1(self):
        self.result = str(self.result) + "1"
        self.Textbar.setPlainText(self.result)
        self.Textbar.setAlignment(QtCore.Qt.AlignRight)
    def click_2(self):
        self.result = str(self.result) + "2"
        self.Textbar.setPlainText(self.result)
        self.Textbar.setAlignment(QtCore.Qt.AlignRight)
    def click_3(self):
        self.result = str(self.result) + "3"
        self.Textbar.setPlainText(self.result)
        self.Textbar.setAlignment(QtCore.Qt.AlignRight)
    def click_4(self):
        self.result = str(self.result) + "4"
        self.Textbar.setPlainText(self.result)
        self.Textbar.setAlignment(QtCore.Qt.AlignRight)
    def click_5(self):
        self.result = str(self.result) + "5"
        self.Textbar.setPlainText(self.result)
        self.Textbar.setAlignment(QtCore.Qt.AlignRight)
    def click_6(self):
        self.result = str(self.result) + "6"
        self.Textbar.setPlainText(self.result)
        self.Textbar.setAlignment(QtCore.Qt.AlignRight)
    def click_7(self):
        self.result = str(self.result) + "7"
        self.Textbar.setPlainText(self.result)
        self.Textbar.setAlignment(QtCore.Qt.AlignRight)
    def click_8(self):
        self.result = str(self.result) + "8"
        self.Textbar.setPlainText(self.result)
        self.Textbar.setAlignment(QtCore.Qt.AlignRight)
    def click_9(self):
        self.result = str(self.result) + "9"
        self.Textbar.setPlainText(self.result)
        self.Textbar.setAlignment(QtCore.Qt.AlignRight)
    def click_0(self):
        self.result = str(self.result) + "0"
        self.Textbar.setPlainText(self.result)
        self.Textbar.setAlignment(QtCore.Qt.AlignRight)
    def click_dot(self):
        self.result = str(self.result) + "."
        self.Textbar.setPlainText(self.result)
        self.Textbar.setAlignment(QtCore.Qt.AlignRight)
    def click_plus(self):
        self.result = str(self.result) + "+"
        self.Textbar.setPlainText(self.result)
        self.Textbar.setAlignment(QtCore.Qt.AlignRight)
    def click_multi(self):
        self.result = str(self.result) + "*"
        self.Textbar.setPlainText(self.result)
        self.Textbar.setAlignment(QtCore.Qt.AlignRight)
    def click_minus(self):
        self.result = str(self.result) + "-"
        self.Textbar.setPlainText(self.result)
        self.Textbar.setAlignment(QtCore.Qt.AlignRight)
    def click_divid(self):
        self.result = str(self.result) + "/"
        self.Textbar.setPlainText(self.result)
        self.Textbar.setAlignment(QtCore.Qt.AlignRight)
    def click_bracketopen(self):
        self.result = str(self.result) + "("
        self.Textbar.setPlainText(self.result)
        self.Textbar.setAlignment(QtCore.Qt.AlignRight)
    def click_bracketclose(self):
        self.result = str(self.result) + ")"
        self.Textbar.setPlainText(self.result)
        self.Textbar.setAlignment(QtCore.Qt.AlignRight)
    def click_power(self):
        self.result = str(self.result) + "^"
        self.Textbar.setPlainText(self.result)
        self.Textbar.setAlignment(QtCore.Qt.AlignRight)
    def click_sqrt(self):
        self.result = "sqrt(" + str(self.result) +")"
        self.Textbar.setPlainText(self.result)
        self.Textbar.setAlignment(QtCore.Qt.AlignRight)
    def click_Clear(self):
        self.result = ""
        self.Textbar.setPlainText(self.result)
        self.Textbar.setAlignment(QtCore.Qt.AlignRight)
    def click_plus_minus(self):
        self.result = str(self.result) + "+-"
        self.Textbar.setPlainText(self.result)
        self.Textbar.setAlignment(QtCore.Qt.AlignRight)
    def click_Delete(self):
        self.result = str(self.result)[:-1] 
        self.Textbar.setPlainText(self.result)
        self.Textbar.setAlignment(QtCore.Qt.AlignRight)

    def click_as(self):
        self.result = int(self.result)
        List__result = str(self.result).split(".")
        if len(List__result)==2:
            if int(List__result[1]) == 0:
                Precision = 0
            else:
                Precision = len(List__result[1])
            if Precision >= 6:
                Precision = 6
        else:
            Precision = 0
        self.Precision = "%." + str(Precision) + "f"
        self.Textbar.setPlainText(self.Precision % self.result)
        self.Textbar.setAlignment(QtCore.Qt.AlignRight)
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.label.setText(_translate("MainWindow", "Calculator by ChiNoMyA"))
        self.button_1.setText(_translate("MainWindow", "1"))
        self.button_2.setText(_translate("MainWindow", "2"))
        self.button_3.setText(_translate("MainWindow", "3"))
        self.button_4.setText(_translate("MainWindow", "4"))
        self.button_5.setText(_translate("MainWindow", "5"))
        self.button_6.setText(_translate("MainWindow", "6"))
        self.button_7.setText(_translate("MainWindow", "7"))
        self.button_8.setText(_translate("MainWindow", "8"))
        self.button_9.setText(_translate("MainWindow", "9"))
        self.button_0.setText(_translate("MainWindow", "0"))
        self.button_dot.setText(_translate("MainWindow", "."))
        self.button_plus.setText(_translate("MainWindow", "+"))
        self.button_multi.setText(_translate("MainWindow", "x"))
        self.button_minus.setText(_translate("MainWindow", "-"))
        self.button_divid.setText(_translate("MainWindow", "/"))
        self.button_bracketopen.setText(_translate("MainWindow", "("))
        self.button_bracketclose.setText(_translate("MainWindow", ")"))
        self.button_power.setText(_translate("MainWindow", "x^2"))
        self.button_sqrt.setText(_translate("MainWindow", "√2"))
        self.button_Clear.setText(_translate("MainWindow", "C"))
        self.button_plus_minus.setText(_translate("MainWindow", "+/-"))
        self.button_Delete.setText(_translate("MainWindow", "del"))
        self.button_as.setText(_translate("MainWindow", "="))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
